In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
df = pd.read_csv('/home/abhishek/Documents/GDP.csv')

In [3]:
df.head(10)

,Year,Afghanistan,Angola,Albania,United Arab Emirates,Argentina,Armenia,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Burkina Faso,Bangladesh,Bulgaria,Bahrain,Bosnia and Herzegovina,Belarus,Bolivia (Plurinational State of),Brazil,Barbados,Botswana,Central African Republic,Canada,Switzerland,Chile,China,Côte d'Ivoire,Cameroon,D.R. of the Congo,Congo,Colombia,Comoros,Cabo Verde,Costa Rica,Czechoslovakia,Cuba,Cyprus,Czech Republic,Germany,Djibouti,Dominica,Denmark,Dominican Republic,Algeria,Ecuador,Egypt,Spain,Estonia,Ethiopia,Finland,France,Gabon,United Kingdom,Georgia,Ghana,Guinea,Gambia,Guinea-Bissau,Equatorial Guinea,Greece,Guatemala,"China, Hong Kong SAR",Honduras,Croatia,Haiti,Hungary,Indonesia,India,Ireland,Iran (Islamic Republic of),Iraq,Iceland,Israel,Italy,Jamaica,Jordan,Japan,Kazakhstan,Kenya,Kyrgyzstan,Cambodia,Republic of Korea,Kuwait,Lao People's DR,Lebanon,Liberia,Libya,Saint Lucia,Sri Lanka,Lesotho,Lithuania,Luxembourg,Latvia,Morocco,Republic of Moldova,Madagascar,Mexico,TFYR of Macedonia,Mali,Malta,Myanmar,Montenegro,Mongolia,Mozambique,Mauritania,Mauritius,Malawi,Malaysia,Namibia,Niger,Nigeria,Nicaragua,Netherlands,Norway,Nepal,New Zealand,Oman,Pakistan,Panama,Peru,Philippines,Poland,Puerto Rico,D.P.R. of Korea,Portugal,Paraguay,State of Palestine,Qatar,Romania,Russian Federation,Rwanda,Saudi Arabia,Sudan (Former),Senegal,Singapore,Sierra Leone,El Salvador,Serbia,Sao Tome and Principe,Former USSR,Slovakia,Slovenia,Sweden,Swaziland,Seychelles,Syrian Arab Republic,Chad,Togo,Thailand,Tajikistan,Turkmenistan,Trinidad and Tobago,Tunisia,Turkey,"Taiwan, Province of China",U.R. of Tanzania: Mainland,Uganda,Ukraine,Uruguay,United States,Uzbekistan,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Former Yugoslavia,South Africa,Zambia,Zimbabwe
0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,116",886,NaN,NaN,NaN,956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,275",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,116","1,116",NaN,"1,116","1,407",NaN,"1,116",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,116",897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,730.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,164",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,466",NaN,NaN,NaN,NaN,NaN,598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,225",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,956,NaN,NaN,NaN,NaN,NaN,NaN,"1,151",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,307",NaN,NaN,NaN,NaN,NaN,"1,010",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,222",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,181",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,052",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,084",NaN,NaN,NaN,NaN,NaN,927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1252.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,320",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1253.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,328",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1254.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,317",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1255.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,285",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
gr=df.groupby(['Year',"Afghanistan"])

In [9]:
gr.first()

,,Angola,Albania,United Arab Emirates,Argentina,Armenia,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Burkina Faso,Bangladesh,Bulgaria,Bahrain,Bosnia and Herzegovina,Belarus,Bolivia (Plurinational State of),Brazil,Barbados,Botswana,Central African Republic,Canada,Switzerland,Chile,China,Côte d'Ivoire,Cameroon,D.R. of the Congo,Congo,Colombia,Comoros,Cabo Verde,Costa Rica,Czechoslovakia,Cuba,Cyprus,Czech Republic,Germany,Djibouti,Dominica,Denmark,Dominican Republic,Algeria,Ecuador,Egypt,Spain,Estonia,Ethiopia,Finland,France,Gabon,United Kingdom,Georgia,Ghana,Guinea,Gambia,Guinea-Bissau,Equatorial Guinea,Greece,Guatemala,"China, Hong Kong SAR",Honduras,Croatia,Haiti,Hungary,Indonesia,India,Ireland,Iran (Islamic Republic of),Iraq,Iceland,Israel,Italy,Jamaica,Jordan,Japan,Kazakhstan,Kenya,Kyrgyzstan,Cambodia,Republic of Korea,Kuwait,Lao People's DR,Lebanon,Liberia,Libya,Saint Lucia,Sri Lanka,Lesotho,Lithuania,Luxembourg,Latvia,Morocco,Republic of Moldova,Madagascar,Mexico,TFYR of Macedonia,Mali,Malta,Myanmar,Montenegro,Mongolia,Mozambique,Mauritania,Mauritius,Malawi,Malaysia,Namibia,Niger,Nigeria,Nicaragua,Netherlands,Norway,Nepal,New Zealand,Oman,Pakistan,Panama,Peru,Philippines,Poland,Puerto Rico,D.P.R. of Korea,Portugal,Paraguay,State of Palestine,Qatar,Romania,Russian Federation,Rwanda,Saudi Arabia,Sudan (Former),Senegal,Singapore,Sierra Leone,El Salvador,Serbia,Sao Tome and Principe,Former USSR,Slovakia,Slovenia,Sweden,Swaziland,Seychelles,Syrian Arab Republic,Chad,Togo,Thailand,Tajikistan,Turkmenistan,Trinidad and Tobago,Tunisia,Turkey,"Taiwan, Province of China",U.R. of Tanzania: Mainland,Uganda,Ukraine,Uruguay,United States,Uzbekistan,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Former Yugoslavia,South Africa,Zambia,Zimbabwe
Year,Afghanistan,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1950.0,"1,156","1,677","1,596","25,182","7,949",None,"11,815","5,907",None,595,"8,706","1,627",756,861,"2,632","3,354",None,None,"3,011","2,236","3,390",489,"1,307","11,622","11,541","5,880",799,"1,659","1,070",909,"1,693","3,432",534,"1,006","3,129","5,581","2,638","2,885",None,"6,186","3,459",980,"11,067","1,637","2,176","2,970","1,451","3,464",None,622,"6,779","8,266","2,958","11,061",None,"1,788",520,982,462,797,"3,052","3,323","4,082","2,018",None,"1,790","3,953","1,280",987,"5,504","2,742","2,174","8,498","4,490","5,582","2,115","2,651","3,062",None,"1,038",None,768,998,"46,031",697,"3,872","3,151",620,"1,231","1,997",631,None,"13,378",None,"2,319",None,"1,516","3,510",None,728,"1,573",631,None,677,"1,806",679,"3,942",516,"2,485","4,009",983,"1,200","2,565","9,558","8,655",802,"13,479",993,"1,025","2,577","3,679","1,706","3,900","3,416",None,"3,325","2,391","1,549","48,436",824,None,"1,020","3,556","1,309","2,007","3,572",902,"2,375",None,"1,278","4,529",None,None,"10,742",604,"2,632","3,838",815,870,"1,302",None,None,"5,856","1,777","2,079","1,460",676,"1,095",None,"7,015","15,240",None,"8,462","1,049","1,452","2,276","4,041","1,054","1,117"
1951.0,"1,170","1,715","1,666","26,634","8,086",None,"11,966","6,311",None,618,"9,161","1,597",776,862,"3,170","3,483",None,None,"3,209","2,279","3,513",497,"1,339","12,007","11,878","6,001",950,"1,686","1,095",995,"1,726","3,427",553,"1,019","3,110","5,617","2,664","2,782",None,"6,704","3,566","1,066","11,056","1,780","2,147","2,925","1,443","3,790",None,630,"7,286","8,705","3,049","11,354",None,"1,808",542,"1,015",489,827,"3,287","3,263","3,688","2,066",None,"1,788","4,296","1,356",993,"5,649","2,668","2,303","8,080","5,035","5,958","2,251","2,702","3,389",None,"1,229",None,775,991,"47,464",706,"5,150","3,257",668,"1,254","2,061",657,None,"12,337",None,"2,324",None,"1,549","3,673",None,740,"1,642",711,None,697,"1,841",698,"4,022",529,"2,295","4,038","1,004","1,262","2,657","9,615","9,038",816,"12,199","1,036",969,"2,491","3,867","1,835","4,001","3,515",None,"3,456","2,373","1,608","48,653","1,046",None,"1,058","3,784","1,334","2,042","3,368",942,"2,361",None,"1,274","4,473",None,None,"11,077",623,"2,778","3,609",834,885,"1,353",None,None,"6,207","1,763","2,299","1,513",743,"1,023",None,"7,548","16,125",None,"9,039","1,078","1,463","2,335","4,130","1,097","1,151"
1952.0,"1,189","1,755","1,667","27,490","7,519",None,"11,824","6,323",None,626,"9,035","1,565",797,874,"3,017","3,614","1,894",None,"3,237","2,377","3,655",504,"1,369","12,486","12,016","6,252","1,047","1,714","1,122","1,065","1,758","3,529",559,"1,031","3,370","5,735","2,844","3,017",None,"7,257","3,585","1,121","11,086","1,868","2,193","3,202","1,435","4,105",None,636,"7,450","8,869","3,143","11,303",None,"1,728",550,"1,022",516,845,"3,272","3,226","3,846","2,083","2,738","1,860","4,403","1,401","1,003","5,805","2,597","2,482","8,823","4,828","6,371","2,397","2,751","3,724",None,"1,063",None,803,"1,038","47,856",714,"5,327","3,277",697,"1,288","2,093",666,None,"13,162",None,"2,327",None,"1,581","3,706","2,150",752,"1,701",716,"1,784",719,"1,878",717,"4,002",540,"2,345","4,066","1,023","1,323","3,016","9,698","9,267",835,"12,427","1,079",950,"2,557","3,964","1,890","4,018","3,730",None,"3,445","2,273","1,669","47,990","1,031",None,"1,071","3,937","1,363","2,077","2,342",958,"2,472","2,032","1,272","4,682",None,"3,934","11,152",628,"2,821","4,441",851,899,"1,385",None,None,"6,282","1,945","2,522","1,639",740,"1,058",None,"7,353","16,444",None,"9,309","1,106","1,473","2,125","4,175","1,140","1,154"
1953.0,"1,240","1,795","1,736","29,358","7,769",None,"11,963","6,594",None,641,"9,274","1,492",816,872,"3,323","3,747","1,878",None,"2,869","2,418","3,803",513,"1,400","12,726","12,471","6,582","1,157","1,741","1,148","1,105","1,790","3,629",571,"1,044","3,751","5,649","2,611","3,274",None,"7,818","3,633","1,073","11,623","1,790","2,182","3,185","1,425","4,066",None,662,"7,415","9,060","3,237","11,709",None,"1,916",563,"1,036",547,867,"3,681","3,239","3,982","2,184","2,952","1,771","4,441","1,451","1,047","5,973","2,531","3,394","8,886","4,638","6,790","2,695","2,801","3,944",None,"1,009",None,792,"1,317","49,989",722,"5,968","3,325",685,"1,326","2,071",682,None,"13,256",None,"2,340",None,"1,613","3,602","2,240",765,"1,779",724,"1,570",741,"1,911",736,"4,006",553,"2,295","4,125","1,042","1,325","2,997","10,429","9,540",877,"12,522","1,127","1,015","2,649","4,111","1,999","4,173","3,937",None,"3,663","2,276","1,733","49,284","1,148",None,"1,090","4,246","1,388","2,110","2,794",982,"2,577","2,348","1,272","4,803",None,"4,106","11,389",638,"2,868","4,916",870,913,"1,490",None,None,"6,303","1,983","2,745","1,728",697,"1,076",None,"8,030","16,917",None,"9,500","1,135","1,482","2,289","4,264","1,184","1,211"
1954.0,"1,245","1,720","1,785","31,695","7,938",None,"12,419","7,261",None,665,"9,610","1,505",838,872,"3,228","3,883","1,847",None,"2,868","2,531","3,947",521,"1,431","12,272","13,171","6,237","1,049","1,769","1,175","1,148","1,822","3,759",590,"1,030","3,649","5,821","2,611","3,287",None,"8,364","3,743","1,098","11,749","1,833","2,291","3,352","1,417","4,328",None,650,"7,973","9,428","3,335","12,145",None,"2,099",587,"1,068",652,901,"3,759","3,194","4,124","1,997","3,193","1,884","4,543","1,517","1,071","6,048","2,464","3,926","9,446","5,378","7,092","2,962","2,848","4,116",None,"1,095",None,864,"1,373","52,920",730,"6,668","3,427",662,"1,364","2,066",708,None,"13,238",None,"2,353",None,"1,645","3,851","2,289",778,"1,844",668,"1,581",764,"1,924",756,"4,095",566,"2,375","4,254","1,063","1,382","3,178","11,010","9,923",886,"13,936","1,173","1,014","2,681","4,117","2,085","4,328","4,081",None,"3,814","2,255","1,801","51,490","1,165",None,"1,127","4,642","1,417","2,146","3,202","1,023","2,536","2,236","1,325","4,951",None,"4,623","11,799",658,"2,992","5,504",888,928,"1,431",None,None,"6,239","1,991","2,609","1,825",735,"1,033",None,"8,273","16,512",None,"10,020","1,167","1,492","2,335","4,404","1,231","1,231"
1955.0,"1,246","1,830","1,882","31,374","8,348",None,"12,795","8,054",None,674,"10,010","1,474",859,810,"3,424","4,014","2,265",None,"2,954","2,675","4,133",529,"1,462","13,072","13,999","6,341","1,119","1,796","1,202","1,170","1,854","3,783",596,"1,034","3,921","6,252","2,638","3,360",None,"9,240","3,765","1,130","11,788","1,886","2,303","3,349","1,411","4,442",None,673,"8,284","9,881","3,437","12,541",None,"1,913",598,"1,074",622,915,"4,007","3,170","4,280","1,986","3,749","1,776","4,894","1,537","1,078","6,248","2,397","3,663","10,096","5,899","7,453","3,220","2,590","4,417",None,"1,144",None,826,"1,411","51,417",738,"7,010","3,454",807,"1,400","2,131",719,None,"13,818",None,"2,364",None,"1,677","4,060","2,766",791,"1,930",744,"2,099",786,"2,007",776,"4,095",564,"2,327","4,288","1,082","1,379","3,288","11,678","10,044",894,"13,908","1,221","1,012","2,766","4,309","2,165","4,454","4,221",None,"3,945","2,299","1,867","49,632","1,419",None,"1,138","4,658","1,446","2,179","2,946","1,044","2,590","2,584","1,191","5,281",None,"5,002","12,060",663,"2,979","4,844",907,940,"1,506",None,None,"6,880","1,855","2,754","1,895",733,"1,071",None,"8,176","17,370",None,"10,501","1,195","1,502","2,721","4,511","1,173","1,288"
1956.0,"1,278","1,769","1,902","32,481","8,424",None,"12,924","8,603",None,687,"10,237","1,444",883,878,"3,392","4,141","1,932",None,"2,719","2,672","4,390",537,"1,492","13,791","14,507","6,285","1,189","1,824","1,229","1,224","1,884","3,811",606,"1,047","3,668","6,551","2,740","3,688",None,"9,846","3,810","1,203","11,858","2,008","2,475","3,381","1,443","4,769",None,682,"8,440","10,278","3,539","12,639",None,"1,970",610,"1,086",703,940,"4,313","3,347","4,450","2,080","3,564","1,897","4,632","1,533","1,117","6,212","2,541","3,808","10,323","6,153","7,745","3,491","3,410","4,699",None,"1,173",None,912,"1,382","52,404",744,"6,663","3,494",950,"1,433","2,091",735,None,"14,343",None,"2,313",None,"1,709","4,213","2,799",803,"2,150",781,"1,906",810,"1,980",797,"4,106",599,"2,399","4,340","1,103","1,309","3,186","11,953","10,480",925,"14,346","1,274","1,017","2,836","4,385","2,248","4,565","4,525",None,"4,087","2,335","1,930","50,628","1,223",None,"1,156","4,901","1,556","2,212","3,241","1,070","2,715","2,447","1,256","5,684",None,"4,889","12,428",673,"2,949","5,592",926,955,"1,482",None,None,"8,064","1,949","2,777","1,926",724,"1,100",None,"8,225","17,397",None,"11,136","1,218","1,508","2,560","4,645","1,280","1,422"
1957.0,"1,253","1,908","2,023","32,329","8,705",None,"12,895","9,111",None,701,"10,353","1,414",905,845,"3,714","4,262","2,214",None,"2,573","2,793","4,646",544,"1,522","13,719","14,668","6,758","1,195","1,852","1,256","1,237","1,914","3,826",615,"1,012","3,835","6,886","2,922","3,848",None,"10,348","3,848","1,239","12,696","2,066","2,699","3,437","1,474","4,900",None,665,"8,751","10,779","3,642","12,779",None,"1,978",622,"1,097",744,958,"4,557","3,424","4,626","2,107","4,203","1,752","5,051","1,613","1,084","6,239","2,817","3,666","10,079","6,363","8,158","3,934","3,354","4,999",None,"1,176",None,947,"1,467","50,126",751,"6,599","3,537",958,"1,479","2,067",749,None,"14,961",None,"2,263",None,"1,741","4,403","3,062",816,"2,144",813,"2,125",835,"1,986",816,"4,136",610,"2,319","4,398","1,122","1,323","3,351","12,137","10,697",915,"14,418","1,325","1,036","3,054","4,479","2,299","4,721","4,729",None,"4,238","2,381","2,000","49,973","1,427",None,"1,173","4,972","1,492","2,246","2,874","1,093","2,775","3,147","1,245","5,700",None,"5,432","12,899",682,"3,008","5,781",945,969,"1,451",None,None,"8,518","1,847","2,920","1,997",720,"1,116",None,"8,176","17,406",None,"11,923","1,235","1,516","3,045","4,704","1,302","1,473"
1958.0,"1,298","1,978","2,114","32,473","9,083",None,"13,238","9,416",None,708,"10,268","1,435",929,813,"3,998","4,366","2,284",None,"2,576","3,005","4,855",550,"1,553","13,603","14,644","6,958","1,173","1,879","1,283","1,176","1,946","3,798",618,"1,004","4,152","7,348","2,922","3,660",None,"10,739","3,840","1,261","12,903","2,104","2,740","3,441","1,510","5,176",None,674,"8,725","10,927","3,749","12,698",None,"1,892",630,"1,097",762,974,"4,723","3,470","4,799","2,106","4,285","1,855","5,367","1,530","1,141","6,169","3,057","3,974","10,568","6,550","8,544","3,918","3,539","5,243",None,"1,156",None,969,"1,518","47,671",759,"5,510","3,545","1,020","1,545","2,074",764,None,"15,093",None,"2,214",None,"1,773","4,501","3,301",830,"2,255",778,"2,072",859,"2,040",837,"4,132",618,"2,252","4,409","1,143","1,270","3,258","11,926","10,603",956,"14,641","1,380","1,025","3,014","4,372","2,308","4,873","4,784",None,"4,259","2,453","2,048","50,042","1,323",None,"1,178","5,107","1,513","2,278","2,880","1,109","2,751","3,022","1,364","6,020",None,"6,005","12,884",684,"3,027","4,844",966,982,"1,457",None,None,"8,941","2,058","2,973","2,056",708,"1,092",None,"7,788","16,946",None,"11,615","1,251","1,522","3,084","4,685","1,237","1,444"
1959.0,"1,307","1,953","2,201","34,153","8,354",None,"13,753","9,645",None,736,"10,533","1,457",953,838,"4,278","4,457","2,667",None,"2,511","3,201","5,053",559,"1,581","13,829","15,470","6,409","1,117","1,898","1,310","1,191","1,977","3,942",639,"1,087","4,141","7,619","3,006","3,814",None,"11,440","3,948","1,226","13,767","2,047","3,178","3,524","1,545","5,085",None,681,"9,172","11,124","3,857","13,134",None,"2,106",655,"1,129",765,"1,015","4,846","3,524","4,957","2,090","4,640","1,734","5,553","1,570","1,143","6,437","3,226","4,022","10,702","7,175","9,011","4,050","3,645","5,665",None,"1,148",None,"1,036","1,556","47,131",765,"5,818","3,655","1,063","1,623","2,048",773,None,"15,382",None,"2,165",None,"1,804","4,497","3,381",845,"2,278",885,"2,200",885,"2,109",858,"4,251",626,"2,338","4,549","1,162","1,288","3,204","12,333","10,957",971,"15,350","1,435","1,009","3,124","4,275","2,393","4,935","5,161",None,"4,454","2,385","2,146","52,436","1,478",None,"1,216","5,512","1,647","2,308","3,239","1,157","2,788","3,885","1,221","5,848",None,"6,304","13,211",706,"3,102","4,881",983,995,"1,581",None,None,"9,154","1,940","3,030","2,118",724,"1,116",None,"7,450","17,900",None,"12,078","1,262","1,529","3,547","4,774","1,458","1,474"
1960.0,"1,326","1,997","2,313","35,758","8,861",None,"14,013","10,391",None,733,"11,081","1,468",971,869,"4,642","4,532","2,871",None,"2,560","3,398","5,316",564,"1,567","13,952","16,358","6,781","1,057","2,002","1,326","1,192","1,999","3,980",679,"1,135","4,328","8,142","2,994","3,496",None,"12,282","4,087","1,245","14,046","2,075","3,328","3,649","1,580","5,037",None,701,"9,931","11,792","3,982","13,780",None,"2,197",671,"1,167",800,"1,101","5,015","3,496","5,088","2,147","5,067","1,809","5,816","1,613","1,200","6,825","3,437","4,360","10,959","7,433","9,430","4,230","3,714","6,354",None,"1,157",None,"1,070","1,548","45,929",771,"5,812","3,674","1,323","1,691","2,064",813,None,"15,870",None,"2,118",None,"1,793","4,723","3,586",851,"2,383",899,"2,439",912,"2,115",913,"4,396",628,"2,439","4,855","1,213","1,307","3,148","13,209","11,483",980,"15,087","1,490","1,031","3,217","4,733","2,353","5,125","5,451",None,"4,712","2,346","2,248","52,299","1,605","5,557","1,224","5,928","1,632","2,303","3,464","1,176","2,813","3,948","1,352","6,288",None,"7,165","13,849",783,"3,257","4,819",974,"1,058","1,718",None,None,"9,964","2,141","3,041","2,157",732,"1,137",None,"7,643","18,057",None,"12,116","1,274","1,537","3,778","4,847","1,530","1,495"
1961.0,"1,309","2,225","2,332","36,949","9,344",None,"13,793","10,882",None,615,"11,561","1,482","1,004",899,"4,897","4,594","2,925",None,"2,555","3,585","5,683",575,"1,597","14,080","17,308","6,923",874,"2,114","1,321","1,041","2,020","4,049",671,"1,173","4,340","8,389","3,068","3,845",None,"12,675","4,114","1,176","14,843","1,964","2,868","3,633","1,643","5,587",None,722,"10,613","12,302","4,415","14,118",None,"2,212",703,"1,318",851,"1,191","5,408","3,532","5,169","2,130","5,404","1,702","6,083","1,690","1,208","7,186","3,622","4,720","10,728","7,964","10,158","4,307","4,280","7,055",None,"1,093",None,"1,031","1,606","41,622",779,"6,027","3,663","1,400","1,747","2,050",813,None,"16,349",None,"2,138",None,"1,795","4,807","3,634",840,"2,361",904,"2,922",939,"2,131","1,055","5,254",644,"2,538","4,787","1,239","1,313","3,277","13,074","12,106",990,"15,533","1,471","1,066","3,462","5,008","2,410","5,461","5,859",None,"4,972","2,396","2,287","48,516","1,725","5,874","1,167","6,481","1,588","2,351","3,623","1,181","2,821","4,038","1,454","6,532",None,"7,760","14,564",861,"2,995","5,050",971,"1,103","1,753",None,None,"10,155","2,289","3,022","2,228",703,"1,093",None,"7,740","18,175",None,"12,231","1,294","1,545","3,950","4,929","1,495","1,524"
1962.0,"1,302","2,128","2,409","38,654","9,049",None,"14,389","11,078",None,657,"12,087","1,400","1,060",877,"5,252","4,672","2,868",None,"2,636","3,711","5,923",582,"1,525","14,787","17,794","7,071",926,"2,128","1,339","1,223","2,039","4,135",714,"1,207","4,439","8,454","2,974","4,211",None,"13,106","4,057","1,333","15,537","2,222","2,284","3,716","1,712","6,083",None,736,"10,869","12,859","4,497","14,131",None,"2,257",741,"1,262",899,"1,310","5,577","3,543","5,780","2,174","5,509","1,828","6,315","1,653","1,208","7,390","3,586","4,809","11,435","8,396","10,882","4,339","4,176","7,614",None,"1,117",None,"1,084","1,620","42,150",787,"6,089","3,612","1,788","1,798","2,067",918,None,"16,370",None,"2,158",None,"1,800","4,881","3,666",827,"2,260",966,"2,847",966,"2,232","1,019","5,144",626,"2,609","5,324","1,341","1,349","3,521","13,770","12,347",998,"15,511","1,728","1,114","3,647","5,230","2,450","5,325","6,183",None,"5,308","2,499","2,381","46,304","1,776","6,229","1,296","7,085","1,653","2,370","3,775","1,216","3,062","4,237","1,549","6,599",None,"8,027","15,093","1,017","3,174","6,051","1,004","1,117","1,831",None,None,"10,383","2,198","3,142","2,326",746,"1,106",None,"7,498","18,976",None,"12,848","1,411","1,554","4,041","5,067","1,443","1,497"
1963.0,"1,298","2,200","2,491","39,889","8,695",None,"14,983","11,454",None,673,"12,532","1,430","1,039",947,"5,448","4,772","3,174",None,"2,742","3,623","6,033",591,"1,492","15,248","18,438","7,336","1,034","2,378","1,366","1,248","2,059","4,140",846,"1,237","4,653","8,241","2,958","4,423",None,"13,367","4,092","1,372","15,513","2,291","2,818","3,698","1,785","6,639",None,818,"11,148","13,330","4,599","14,583",None,"2,270",689,"1,232",932,"1,486","6,122","3,762","6,381","2,177","6,059","1,675","6,644","1,557","1,242","7,685","3,867","4,578","12,366","8,915","11,576","4,395","4,222","8,176",None,"1,138",None,"1,135","1,721","40,377",794,"5,973","3,598","2,322","1,849","2,058",995,None,"16,766",None,"2,179",None,"1,747","5,118","4,261",866,"2,263",977,"3,217",996,"2,106",944,"5,745",599,"2,660","5,710","1,443","1,433","3,781","14,078","12,723","1,006","16,150","1,758","1,152","3,877","5,314","2,542","5,582","6,693",None,"5,585","2,504","2,479","44,912","1,922","6,405","1,140","7,516","1,562","2,402","4,049","1,218","3,096","4,713","1,643","6,352",None,"8,871","15,808","1,047","3,384","5,855",972,"1,143","1,921",None,None,"10,708","2,480","3,374","2,463",770,"1,197",None,"7,450","19,514",None,"13,232","1,406","1,568","4,481","5,294","1,438","1,436"

In [17]:
plt.figure(figsize=(19,9))

# uniform_data = np.random.rand(10, 12)

ax = sns.heatmap()

/home/abhishek/.local/lib/python3.10/site-packages/seaborn/matrix.py:105: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  plot_data = np.asarray(data)

ValueError: setting an array element with a sequence.